rust_input: crate::api
rust_root: .
dart_output: ../../app/lib/core/ffi/generated
rust_output: src/bridge_generated.rs
c_output: ios/bridge_generated.h
duplicated_c_output:
  - macos/bridge_generated.h
  - windows/bridge_generated.h
deps_check: true
